### ISSUE TITLE
Fail better if .profile file can't be modified

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup.rs#292]
Installation will fail if `~/.profile` can't be modified. This may or not be the right thing to do, but it should fail gracefully, not with the default I/O error.

**Comment by C-Saunders** [comment]
I started looking into this because it seemed accessible, but I want to check my understanding, if possible, before continuing.

It seems like [writing is initiated here](https://github.com/rust-lang/rustup.rs/blob/master/src/cli/self_update.rs#L1110) and [happens here](https://github.com/rust-lang/rustup.rs/blob/master/src/utils/utils.rs#L57), and [a somewhat specific error message](https://github.com/rust-lang/rustup.rs/blob/master/src/errors.rs#L50) should result in the case of a missing permission.

Do you think the message should be more specific? Or maybe I am way off and looking in the wrong place?

**Comment by kinnison** [comment]
I think that it may be worthwhile to, instead of using `?` in the first place, instead `match` on the result of `utils::append_file()` and make a better error report *or* use `.chain_error()` again to construct a more specific error message about amending the shell profile.
