### ISSUE TITLE
Add telemetry files to a .tar.gz

### ISSUE THREAD

**Issue by peschkaj** [rust-lang/rustup.rs#369]
At a certain point, we can safely move previous telemetry into a compressed file. This will make it easier to move logs up into some kind of "cloud" for later processing.

This should just add every log file, apart from today's, into a `.tar.gz`. An optional `cleanup` parameter will cause rustup to delete the files that have been moved into the `.tar.gz`.

Since this isn't on the analysis path, this won't need any changes to that path. Long term, it might make more sense to do something more sophisticated where we compress data by week and produce a summarized view of the week... but this is enough for now.

**Comment by brson** [comment]
Sounds good!

**Comment by brson** [comment]
Last time we talked about this we were considering looking into Google Analytics instead of rolling our own backend, so this *may* not be necessary.

Of course using Google Analytics means that we wouldn't get any local analysis tools, which would be useful to individual developers.

Tradeoffs either way, but what's most important is getting something going.

**Comment by peschkaj** [comment]
I think that Google Analytics is probably the better long term route. I'll comment over on that issue as to why I think so.

**Comment by kinnison** [comment]
We removed telemetry support quite a while ago.
