### ISSUE TITLE
White fonts tough to read on a white terminal

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustup.rs#433]
Playing around locally it looks like the installer has two headers in white fonts which end up being tough to read on a white terminal. Unfortunately I'm on a train and can't upload a screenshot right this second, but maybe this rings a bell?

**Comment by Diggsey** [comment]
The windows console does not support the "bold" attribute, so whenever `attr(bold)` fails, it falls back to setting the text colour to bright white. Without the fall-back there's almost no colour support on windows since we almost exclusively use the bold attribute.

We'll need some way to get the default foreground colour from term, and then we can swap the brightness on that colour to use as the fall-back in case bold is not supported. Are you using it on windows? If not many people use a white background on the windows console, maybe only using the fallback on windows would be a temporary solution?

**Comment by alexcrichton** [comment]
Nah this was on OSX

**Comment by goertzenator** [comment]
Here's a screenshot of poor coloring on KDE Konsole (linux) with the Solarized Light color scheme.  Barely readable text beside the mouse cursor.  The initial "Welcome to Rust!" is also hard to see.

![image](https://cloud.githubusercontent.com/assets/605072/18754765/70d03a58-80af-11e6-959b-c74f326931af.png)
