### ISSUE TITLE
Cargo's tests fail on osx when using rustup.rs [migrated from rust-lang/cargo]

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rustup.rs#719]
@alexcrichton mentioned he's seen this issue but hadn't figured out a way to reproduce it reliably, sooo I guess I found one!

My original report:

`rustup --version` is `rustup 0.6.3 (a0e2132 2016-08-28)`

I just tried to run cargo's test suite and I get 7 failures, some of which contain the error message "error: no default toolchain configured", which is pointing at rustup.rs as the culprit. 

Further evidence is that when I remove `~/.cargo/bin` from my `PATH`, then run:

``` bash
$ ./configure --disable-cross-tests --disable-optimize
$ make
$ make test
```

All of cargo's tests pass. This uses my checkout of rustc installed to `/usr/local/bin/rustc`, which I just rebuilt today, so it's `rustc 1.13.0-dev (1fca1ab0e 2016-09-10)`.

When I put `~/.cargo/bin` in my path before `/usr/local/bin` so that I'm using rustup.rs, `which rustc` is `~/.cargo/bin/rustc`, and my rustup default is set to nightly, which I updated yesterday, `rustc --version` returns `rustc 1.13.0-nightly (f1f40f850 2016-09-09)`. `rustc -vV` runs without error.

With this setup, if I run the same 3 commands above, I get 7 test failures. [Full output in this gist](https://gist.github.com/carols10cents/4683ffcdca1e66495f02bca7bf6071ef); note the error messages I'm seeing in some of the tests that say "error: no default toolchain configured".

I looked around in rustup's issue tracker a bit for potential situations or causes of this problem, and the only thing I found that looked slightly promising was the aside that "rustc -vV should not be failing with that error even if no default toolchain is configured" [in an issue's comments](https://github.com/rust-lang-nursery/rustup.rs/issues/75#issuecomment-188901151).

@alexcrichton's response:

> Ah yes I've seen this classic error before, and I believe @brson has run into it. I haven't been able to reproduce it yet, but I think it's now been unlocked! The key difference here is that you're using ./configure && make test vs cargo test (which I use locally).
> 
> Cargo tests munge the value of $HOME for subprocesses to prevent polluting or reading the home directory configuration. If you run ./configure && make then this means we're running the rustup rustc binary with $HOME pointing to an arbitrary new location, which greatly confuses rustup. If you run cargo test, however, I believe that the environment variables rustup sets (I think PATH?) end up getting the tests working.
> 
> I suppose my preferred solution here would be to update rustup to work if $HOME isn't set (if that's possible) and we can perhaps investigate other alternatives if that doesn't work.

**Comment by alexcrichton** [comment]
I believe the symptom here is:

```rust
$ HOME=/tmp rustc -vV
error: no default toolchain configured
```

That's essentially what happens with the Cargo tests. They correctly run the `rustc` binary that is actually rustup, and then `HOME` is configured to point somewhere else.

**Comment by brson** [comment]
What's happening here is that Cargo's makefiles are using its own bootstrap cargo which then in-turn runs test cases that frob `HOME` weirdly, then invoke the local (rustup) rustc. Normally it isn't a problem for Cargo to screw with `HOME` because (rustup) cargo will set rustup-specific environment variables to communicate the proper config to (rustup) rustc. In this case though we're mixing rustup tools with non-rustup tools and things go bad. That's why this only happens when running `make check` and not `cargo test`.

Since this is a really weird case that cargo's makefiles are inflicting on itself I'm inclined to fix it there. The way to do this is to set `RUSTUP_HOME` to the right value. Unfortunately there's no definitive way to get that value, but it's pretty likely that if `HOME\.multirust` (one day `HOME\.rustup`) exists and `RUSTUP_HOME` is not set, then that is the right value.

**Comment by kinnison** [comment]
Is this still an issue in modern Cargo?

**Comment by carols10cents** [comment]
It does not appear to be, now that Cargo uses `cargo test` rather than `make`. Running `HOME=/tmp rustc -vV` still produces the error message, but that's irrelevant if nothing does that. So I'm closing!

Thank you for pinging this; I totally forgot about it!
