### ISSUE TITLE
Can rustup be used to create a toolchain with nightly Cargo and stable rustc?

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/rustup.rs#755]
If so, how?

**Comment by steveklabnik** [comment]
I don't believe so, but I'm not 100% sure.

**Comment by steveklabnik** [comment]
(At the same time, every cargo is a nightly cargo, so every toolchain comes with a nightly cargo and stable rustc, so it's also not 100% clear exactly what you want)

**Comment by bruno-medeiros** [comment]
> I'm interpreting it as "a toolchain with a stable rust and an arbitrary cargo that's not the one paired with that stable rust"

Yup, that's right. Basically I want to try out this feature from Cargo : https://github.com/rust-lang/cargo/pull/3000 , only available in nightly currently, but otherwise use stable Rust.

**Comment by Diggsey** [comment]
That's not possible with rustup, and it's not something that can ever really be *supported* since cargo is not guaranteed to be compatible with any rustc other than the one it is paired with (although in practice it will probably work with most).

If you want, you could try installing both a stable and nightly toolchain, and manually copy across the cargo binary, but it may just break your toolchain.

**Comment by bruno-medeiros** [comment]
@matklad mentioned "However you could use nightly Cargo with stable rustc!" in the PR comments. However, if that's true that using nightly cargo with stable rustc might introduce instabilities of its own, might as well use the entire nightly toolchain. I guess it won't take that long for things to move into beta anyways. 😮

**Comment by matklad** [comment]
>cargo is not guaranteed to be compatible with any rustc other than the one it is paired with (although in practice it will probably work with most).

Hm, is this really so? I always thought that Cargo can use any `rustc`. At least, there is [some code](https://github.com/rust-lang/cargo/blob/ee3acca1035f41d87a6be91b42daf02c565ae996/src/cargo/util/rustc.rs#L9-L10) for backward compatibility. @alexcrichton could you clarify backwards/forwards compatibility story between Cargo and rustc?

**Comment by matklad** [comment]
Let me add two use cases for this feature:

1) Cargo gains a new useful feature, which you would like to use with otherwise stable toolchain. The recent example would be workspaces. 

2) Rustc gains a new feature, which needs some support from Cargo as well. But support in Cargo is implemented only after the `rustc`, so they may end up in different releases. This what happened with json errors.
